version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: personal-hub-postgres
    environment:
      POSTGRES_DB: personalhub
      POSTGRES_USER: personalhub
      POSTGRES_PASSWORD: personalhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U personalhub -d personalhub"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: personal-hub-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/personalhub
      SPRING_DATASOURCE_USERNAME: personalhub
      SPRING_DATASOURCE_PASSWORD: personalhub
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: