version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: personalhub
      POSTGRES_PASSWORD: personalhub
      POSTGRES_DB: personalhub
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U personalhub"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # render.com style DATABASE_URL
      DATABASE_URL: postgresql://personalhub:personalhub@postgres:5432/personalhub
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: test-secret-key-that-is-at-least-256-bits-long-for-HS256-algorithm-security
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: