spring:
  application:
    name: todo-app-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/personalhub
    username: personalhub
    password: personalhub
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Tokyo
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  
  security:
    user:
      name: admin
      password: admin
  
  mvc:
    throw-exception-if-no-handler-found: true
  
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:your-secret-key-that-is-at-least-256-bits-long-for-HS256-algorithm-security}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
      key-id: ${JWT_KEY_ID:default-key}
  
  oidc:
    issuer: ${OIDC_ISSUER:http://localhost:8080}
    base-url: ${OIDC_BASE_URL:http://localhost:8080}
    authorization-code-ttl: ${OIDC_AUTH_CODE_TTL:600} # 10 minutes in seconds
    access-token-ttl: ${OIDC_ACCESS_TOKEN_TTL:900} # 15 minutes in seconds
    refresh-token-ttl: ${OIDC_REFRESH_TOKEN_TTL:2592000} # 30 days in seconds
    id-token-ttl: ${OIDC_ID_TOKEN_TTL:3600} # 1 hour in seconds

google:
  calendar:
    credentials:
      file: ${GOOGLE_CREDENTIALS_FILE:credentials.json}
    tokens:
      directory:
        path: ${GOOGLE_TOKENS_DIR:tokens}
    oauth:
      client:
        id: ${GOOGLE_CLIENT_ID:}
        secret: ${GOOGLE_CLIENT_SECRET:}
      redirect:
        uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/v1/calendar/sync/auth/callback}
  
  oidc:
    client:
      id: ${GOOGLE_OIDC_CLIENT_ID:}
      secret: ${GOOGLE_OIDC_CLIENT_SECRET:}
    redirect:
      uri: ${GOOGLE_OIDC_REDIRECT_URI:http://localhost:8080/auth/google/callback}
    discovery:
      document:
        url: https://accounts.google.com/.well-known/openid-configuration

github:
  oauth:
    client:
      id: ${GITHUB_CLIENT_ID:}
      secret: ${GITHUB_CLIENT_SECRET:}
    redirect:
      uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/auth/github/callback}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.zametech.todoapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/todo-app.log