name: CI Pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-app-backend
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: todoapp_test
          POSTGRES_USER: todoapp
          POSTGRES_PASSWORD: todoapp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: 'todo-app-backend/pom.xml'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('todo-app-backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests
      run: mvn clean test
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Run integration tests
      run: mvn verify
      env:
        SPRING_PROFILES_ACTIVE: ci
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/todoapp_test
        SPRING_DATASOURCE_USERNAME: todoapp
        SPRING_DATASOURCE_PASSWORD: todoapp

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: todo-app-backend/target/surefire-reports/*.xml
        reporter: java-junit

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: todo-app-backend/target/site/jacoco/jacoco.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          todo-app-backend/target/surefire-reports/
          todo-app-backend/target/failsafe-reports/
          todo-app-backend/target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: todo-app-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: 'todo-app-backend/pom.xml'

    - name: Build application
      run: mvn clean package -DskipTests

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: todo-app-backend/target/*.jar
        retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: todo-app-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: 'todo-app-backend/pom.xml'

    - name: Run OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
      continue-on-error: true

    - name: Upload dependency check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: todo-app-backend/target/dependency-check-report.html

  code-quality:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: todo-app-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: 'todo-app-backend/pom.xml'

    - name: Run SpotBugs
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs
      continue-on-error: true

    - name: Run PMD
      run: mvn pmd:pmd
      continue-on-error: true

    - name: Archive code quality results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-quality-reports
        path: |
          todo-app-backend/target/spotbugs.xml
          todo-app-backend/target/pmd.xml